force-app/main/default/objects/Event__c/fields/Current_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Current_Attendees__c</fullName>
    <label>Current Attendees</label>
    <summaryForeignKey>Event_Registration__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Max_Attendees__c</fullName>
    <label>Max Attendees</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Select Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registration</relationshipLabel>
    <relationshipName>Event_Registration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registered_On__c.field-meta.xml
<CustomField>
    <fullName>Registered_On__c</fullName>
    <label>Registered On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventRegistraionHandler.cls
public class EventRegistraionHandler {
    public static void EventRegistraionBeforeInsert(List<Event_Registration__c> eventRegObj){
       List<Event_Registration__c> existingRegs = [SELECT Event__c, Attendee__c FROM Event_Registration__c];

        Map<Id,Event_Registration__c> alreadyRegisterdUserIdAndEventId = new Map<Id,Event_Registration__c>();
        
        for(Event_Registration__c  existingRecordList: existingRegs){
            alreadyRegisterdUserIdAndEventId.put(existingRecordList.Event__c,existingRecordList);
         }
        
        Map<Id,Event__c> eventObjDetails = new Map<Id,Event__c>();
        
        Set<Id> EventIds = new Set<Id>();
        
        for(Event_Registration__c currentEventRegObj : eventRegObj){
            EventIds.add(currentEventRegObj.Event__c);
            if(currentEventRegObj.Event__c != null && currentEventRegObj.Attendee__c != null){
                currentEventRegObj.Registered_On__c = system.now();
                if(alreadyRegisterdUserIdAndEventId.containsKey(currentEventRegObj.Event__c)){
                   Event_Registration__c eventRegisterdUser = alreadyRegisterdUserIdAndEventId.get(currentEventRegObj.Event__c);
                       if(eventRegisterdUser.Attendee__c == currentEventRegObj.Attendee__c){
                           currentEventRegObj.addError('Already registered ');
                       }
                }
            }
        }
        
        for(Event__c eventObj: [select Id,Max_Attendees__c,Current_Attendees__c from Event__c where Id IN:EventIds ]){
             eventObjDetails.put(eventobj.Id,eventObj);
        }
        
        for(Event_Registration__c currentEventRegObj : eventRegObj){
            if(eventObjDetails.containsKey(currentEventRegObj.Event__c)){
              Event__c eventObj =   eventObjDetails.get(currentEventRegObj.Event__c);
                system.debug('happy'+eventObj);
                if(eventObj.Current_Attendees__c >= eventObj.Max_Attendees__c){
                   currentEventRegObj.addError('Event is full ❁´◡`❁');
                }       
            }
        }
        
        
        
    }       
}