force-app/main/default/objects/Event__c/fields/Event_date__c.field-meta.xml
<CustomField>
    <fullName>Event_date__c</fullName>
    <label>Event date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Registration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Registration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Select Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Registration</relationshipLabel>
    <relationshipName>Event_Registration</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registered_On__c.field-meta.xml
<CustomField>
    <fullName>Registered_On__c</fullName>
    <label>Registered On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/EventController.cls
public class EventController {
    @AuraEnabled
    public static List<Event__c> getEvents(string eventtype,String inputValue){
        System.debug('eventtype' +''+ eventtype);
        String eventlist =    'select Id,Location__c,Event_Type__c,Name,Event_date__c from Event__c where Id != null';
        if(!String.isBlank(eventtype)){
            eventlist += ' AND Event_Type__c =:eventtype';
        }
        if(!String.isBlank(inputValue)){
            eventlist += ' AND Name LIKE \'' + String.escapeSingleQuotes(inputValue) + '%\'';
        }
       return  Database.Query(eventlist);
    }  
    @AuraEnabled
    public static String checkRegistration(String eventId){
        System.debug('eventId '+eventId);
        Id UserId = userInfo.getUserId();
       
        // hum yha se bhi user ki Id nikal skte hai "UserInfo.getUserId()" se;
        List<Event_Registration__c> EventRegistration = [select Id , Name from Event_Registration__c where 	Event__c =:eventId And 	Attendee__c =:UserId] ;
        if(EventRegistration.size() > 0){
            return 'alreadyRegisterd';
                }else {
                    return 'notRegisterd';
                }
    }
    
   @AuraEnabled(cacheable=true)
    public static List<User> getCurrentUser() {
        Id userId = UserInfo.getUserId();
         System.debug('UserId123 '+UserId);
        return [SELECT Id, Name, Email FROM User WHERE Id = :userId];
    }
    
    @AuraEnabled
    public static void eventRegistration(String Name,String eventId,String userId ){
        try{ 
            Event_Registration__c EventRegis = new Event_Registration__c();
        EventRegis.Attendee__c = userId ;
        EventRegis.Event__c = eventId;
        EventRegis.Name = Name;
        EventRegis.Registered_On__c = System.now();
        Database.insert(EventRegis);
        }catch(Exception err){
            System.debug(err);
        }
    }
    
    
    
}